In [2]:
import tensorflow as tf
print(tf.__version__)

2023-12-14 14:08:03.177833: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-14 14:08:03.177900: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-14 14:08:03.287199: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-14 14:08:03.514865: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-14 14:08:04.942175: W tensorflow/compiler/tf2

2.15.0


In [3]:
scalar = tf.constant(7)
scalar

2023-12-14 14:08:07.515646: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-14 14:08:07.832194: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [8., 9.],
                              [9., 1.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 9.,  1.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [2, 2, 2]],
                      [[1, 1, 1,],
                       [4, 4, 4]],
                      [[2, 2, 2],
                       [4, 2, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 2, 2]],

       [[1, 1, 1],
        [4, 4, 4]],

       [[2, 2, 2],
        [4, 2, 1]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2, 3))

random_1, random_2

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>)

**Creating random tensors**

In [16]:
result = tf.equal(random_1, random_2)
result.numpy()

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [17]:
# Shuffle a tensor

In [18]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

not_shuffled, tf.random.shuffle(not_shuffled, seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [ 3,  4],
        [10,  7]], dtype=int32)>)

In [19]:
tf.equal(tf.random.shuffle(not_shuffled, seed=42), tf.random.shuffle(42))

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [20]:
# @tf.function
# def foo():
#   tf.random.set_seed(42)
#   a = tf.random.uniform([1])
#   b = tf.random.uniform([1])
#   c = tf.random.uniform([2], seed=42)
#   return a, b, c

# a, b, c = foo()
# a1, b1, c1 = foo()
# tf.equal(a, b)

In [21]:
import jax.numpy as jnp


e_value = tf.constant(jnp.exp(1.0))
pi_value = tf.constant(jnp.pi)

# Create a TensorFlow variable with NumPy arrays
e_pi_vec = tf.Variable([e_value.numpy(), pi_value.numpy()], dtype=tf.float32)

# Display the TensorFlow variable
print(e_pi_vec)

I0000 00:00:1702559288.121530   27437 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2.7182817, 3.1415927], dtype=float32)>


**If we want out shuffled tensors to be in he same order, we've got use the global level random seed as well as the operation level random seed.**

In [22]:
tf.random.set_seed(10)  # global level random seed
tf.random.shuffle(e_pi_vec, seed=10)  # operation level random seed

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.1415927, 2.7182817], dtype=float32)>

Other way to make tensors:

In [23]:
tf.ones([2, 2, 2, 2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [24]:
tf.zeros([2, 2, 2, 2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

The main difference between NumPy arrays and TensorFlow tensors is tha tensors can be run on a GPU (much faster for numerical computing)

In [25]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

Create a rank 4 tensors (4 dimensions)

In [27]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank) ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank)  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


**Indexing tensors**

Tensors ca be indexed just like Python list

In [31]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [36]:
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [37]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [39]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [42]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
# Convert Unicode code point to a TensorFlow string constant
wizard_string = tf.constant([chr(0x1F9D9)], dtype=tf.string)

# Print the Unicode string
print(wizard_string.numpy()[0].decode('utf-8'))

🧙


***Manipulating tensors(tensor operations)***

In [97]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [98]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [99]:
# 1D tensor (vector)
tensor_1d = tf.constant([1, 2, 3, 4])

# Expand the dimensions along axis 0
tensor_2d = tf.expand_dims(tensor_1d, axis=1)
tensor_3d = tf.expand_dims(tensor_2d, axis=1)
# Print the original and expanded tensors
print("Original Tensor (1D):", tensor_1d)
print("Expanded Tensor (2D):", tensor_2d)
print("Expanded Tensor (3D)", tensor_3d)

Original Tensor (1D): tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Expanded Tensor (2D): tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
Expanded Tensor (3D) tf.Tensor(
[[[1]]

 [[2]]

 [[3]]

 [[4]]], shape=(4, 1, 1), dtype=int32)


In [108]:
X = tf.constant([[10, 20],
                [30, 40],
                [12, 12]], dtype=tf.int32)

Y = tf.constant([[10, 12, 12],
               [10, 10, 10]], dtype=tf.int32)
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40],
        [12, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 12, 12],
        [10, 10, 10]], dtype=int32)>)

In [109]:
tf.matmul(X, tf.reshape(X, shape=[2, 3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 900,  440,  540],
       [1900, 1080, 1380],
       [ 600,  384,  504]], dtype=int32)>

In [114]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [12, 12]], dtype=int32)>

In [115]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 30, 12],
       [20, 40, 12]], dtype=int32)>

In [117]:
tf.matmul(X, tf.transpose(X))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 500, 1100,  360],
       [1100, 2500,  840],
       [ 360,  840,  288]], dtype=int32)>

**The dot product**

tf.matmul()

tf.tensordot()

In [118]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40],
        [12, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 12, 12],
        [10, 10, 10]], dtype=int32)>)

In [120]:
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[300, 320, 320],
       [700, 760, 760],
       [240, 264, 264]], dtype=int32)>

In [121]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[300, 320, 320],
       [700, 760, 760],
       [240, 264, 264]], dtype=int32)>

In [122]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[300, 320, 320],
       [700, 760, 760],
       [240, 264, 264]], dtype=int32)>

In [123]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [12, 12]], dtype=int32)>

In [124]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 30, 12],
       [20, 40, 12]], dtype=int32)>

In [125]:
# Create a new tensor with default datatype (float32)

In [133]:
B = tf.constant([1.7, 7.4])
B.dtype, B

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [134]:
A = tf.constant([1, 7])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

In [135]:
# Reduce precision from 32bit to 16bit (reduced precision)
C = tf.cast(B, dtype=tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [136]:
D = tf.cast(B, dtype=tf.bfloat16)
D

<tf.Tensor: shape=(2,), dtype=bfloat16, numpy=array([1.70312, 7.40625], dtype=bfloat16)>

In [137]:
# Change from int32 to int float32
E = tf.cast(A, dtype=tf.float32)
F = tf.cast(A, dtype=tf.float16)
G = tf.cast(A, dtype=tf.bfloat16)
E, F, G

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=bfloat16, numpy=array([1, 7], dtype=bfloat16)>)

# Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [138]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [139]:
# Get the absolut values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [140]:
# Get the minimum, maximum, mean, and sum of a tensor

In [148]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 56, 45, 60, 29, 96, 27, 22, 22, 22, 67, 37, 76,  9, 23, 63, 22,
       19, 31, 15, 78, 63, 34, 45, 28, 67, 77, 38, 82, 44, 32, 22, 98, 54,
       90, 75, 19, 96, 18, 39, 92, 74,  0, 22, 30,  1, 97, 33, 39, 72])>

In [149]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [150]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [151]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [152]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [153]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2365>

In [159]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=756.93005>

In [161]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.512362>

# Find the positional maximum and minimum

In [166]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [168]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [169]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [171]:
# FInd the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [173]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [174]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [175]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [176]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor (removing all single dimensions)

In [180]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=([1, 1, 1, 1, 50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [181]:
G.ndim

5

In [184]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [185]:
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# One-Hot Encodings

In [187]:
# Create a list of indices
some_list = [0, 1, 2, 3]  # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [189]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dace")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dace',
        b'I also like to dace', b'I also like to dace'],
       [b'I also like to dace', b'yo I love deep learning',
        b'I also like to dace', b'I also like to dace'],
       [b'I also like to dace', b'I also like to dace',
        b'yo I love deep learning', b'I also like to dace'],
       [b'I also like to dace', b'I also like to dace',
        b'I also like to dace', b'yo I love deep learning']], dtype=object)>

# Squaring, log, square root

In [190]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [191]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [198]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [200]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [201]:
# Creaet a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [202]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [203]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [204]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [205]:
# Default types of ech are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))  # Defeault type = float64
tensor_J = tf.constant([3., 7., 10.])           # Defeault type = float32
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [207]:
J = tf.constant([[10, 10, 10],
                [20, 20, 20],
                [30, 30, 30]])
J

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]], dtype=int32)>

In [208]:
J.ndim

2

In [209]:
tf.squeeze(J)
J

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]], dtype=int32)>

In [210]:
J.ndim

2

In [225]:
J = tf.constant([[[10, 10],
                 [20, 20]]])
tf.squeeze(J)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20]], dtype=int32)>

In [212]:
J.ndim

3

In [220]:
tensor = tf.constant([[[1], [2], [3], [4], [5]]])
tensor

<tf.Tensor: shape=(1, 5, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4],
        [5]]], dtype=int32)>

In [222]:
tensor.ndim, tensor.shape

(3, TensorShape([1, 5, 1]))

In [224]:
squeeze_tensor = tf.squeeze(tensor)
squeeze_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>