In [1]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                              [8., 9.],
                              [9., 1.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 9.,  1.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 3],
                       [2, 2, 2]],
                      [[1, 1, 1,],
                       [4, 4, 4]],
                      [[2, 2, 2],
                       [4, 2, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 2, 2]],

       [[1, 1, 1],
        [4, 4, 4]],

       [[2, 2, 2],
        [4, 2, 1]]])>

In [11]:
tensor.ndim

3

In [12]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [14]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2, 3))

random_1, random_2

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>)

**Creating random tensors**

In [15]:
result = tf.equal(random_1, random_2)
result.numpy()

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [16]:
# Shuffle a tensor

In [17]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

not_shuffled, tf.random.shuffle(not_shuffled, seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [ 3,  4],
        [10,  7]])>)

In [18]:
tf.equal(tf.random.shuffle(not_shuffled, seed=42), tf.random.shuffle(42))

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [19]:
# @tf.function
# def foo():
#   tf.random.set_seed(42)
#   a = tf.random.uniform([1])
#   b = tf.random.uniform([1])
#   c = tf.random.uniform([2], seed=42)
#   return a, b, c

# a, b, c = foo()
# a1, b1, c1 = foo()
# tf.equal(a, b)

In [20]:
import jax.numpy as jnp


e_value = tf.constant(jnp.exp(1.0))
pi_value = tf.constant(jnp.pi)

# Create a TensorFlow variable with NumPy arrays
e_pi_vec = tf.Variable([e_value.numpy(), pi_value.numpy()], dtype=tf.float32)

# Display the TensorFlow variable
print(e_pi_vec)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2.7182817, 3.1415927], dtype=float32)>


**If we want out shuffled tensors to be in he same order, we've got use the global level random seed as well as the operation level random seed.**

In [22]:
tf.random.set_seed(10)  # global level random seed
tf.random.shuffle(e_pi_vec, seed=10)  # operation level random seed

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.1415927, 2.7182817], dtype=float32)>

Other way to make tensors:

In [23]:
tf.ones([2, 2, 2, 2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [24]:
tf.zeros([2, 2, 2, 2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

The main difference between NumPy arrays and TensorFlow tensors is tha tensors can be run on a GPU (much faster for numerical computing)

In [25]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [26]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

Create a rank 4 tensors (4 dimensions)

In [28]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [31]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank) ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank)  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


**Indexing tensors**

Tensors ca be indexed just like Python list

In [38]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [42]:
rank_4_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [47]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [48]:
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [49]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [50]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [54]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [56]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [60]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

In [61]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [77]:
# Convert Unicode code point to a TensorFlow string constant
wizard_string = tf.constant([chr(0x1F9D9)], dtype=tf.string)

# Print the Unicode string
print(wizard_string.numpy()[0].decode('utf-8'))

🧙


***Manipulating tensors(tensor operations)***

In [78]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [79]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [85]:
# 1D tensor (vector)
tensor_1d = tf.constant([1, 2, 3, 4])

# Expand the dimensions along axis 0
tensor_2d = tf.expand_dims(tensor_1d, axis=1)
tensor_3d = tf.expand_dims(tensor_2d, axis=1)
# Print the original and expanded tensors
print("Original Tensor (1D):", tensor_1d)
print("Expanded Tensor (2D):", tensor_expanded)
print("Expanded Tensor (3D)", tensor_3d)

Original Tensor (1D): tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Expanded Tensor (2D): tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
Expanded Tensor (3D) tf.Tensor(
[[[1]]

 [[2]]

 [[3]]

 [[4]]], shape=(4, 1, 1), dtype=int32)
